In [15]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torch.utils.data import sampler

import torchvision.datasets as dset
import torchvision.transforms as T

import numpy as np

In [6]:
num_inputs = 2
input_shape = (4, 5, 6)
output_dim = 3

input_size = num_inputs * np.prod(input_shape)
weight_size = output_dim * np.prod(input_shape)

X_train = np.linspace(-0.1, 0.5, num=input_size).reshape(num_inputs, *input_shape)
print(X_train.shape[0])
print(len(X_train[0]))
X_train = X_train.reshape(num_inputs, -1)
print(X_train.shape)

2
4
(2, 120)


In [2]:
print([{'mode': 'train'} for i in range(10)])

[{'mode': 'train'}, {'mode': 'train'}, {'mode': 'train'}, {'mode': 'train'}, {'mode': 'train'}, {'mode': 'train'}, {'mode': 'train'}, {'mode': 'train'}, {'mode': 'train'}, {'mode': 'train'}]


In [3]:
d = 0.5
d = d != 1
print(d)

True


In [4]:
a = [10, 18]
a.append(19)
print(a)

[10, 18, 19]


In [12]:
grads = {
    'bla1': 11.0,
    'bla6': 17.0,
    'bla2': 12.0,
    'bla3': 13.0,
    'bla5': 15.0,
    'bla4': 14.0,
    
    
}
print(sorted(grads))

['bla1', 'bla2', 'bla3', 'bla4', 'bla5', 'bla6']


In [3]:
dx = np.array([[1,2,3],[5,6,7]])
cache += dx**2
print(cache)
print(np.sqrt(cache))
x += - learning_rate * dx / (np.sqrt(cache))

NameError: name 'cache' is not defined

In [13]:
x = np.array([[1,2,3],[5,6,7]])
print(x)

print('---')
a = [1,2]
print(a)
print('---')
print(np.subtract(x.T,a).T)
print(np.sum(x, axis = 0))

[[1 2 3]
 [5 6 7]]
---
[1, 2]
---
[[0 1 2]
 [3 4 5]]
[ 6  8 10]


In [18]:
x = np.array([[-0.01968568,  0.00217895,  0.00339866, -0.02325224, -0.0221614 ,  0.02105142,
   0.0290504 , -0.03711821 ,-0.00844577 , 0.00813935, -0.01596476 , 0.00103281,
  -0.0114362,   0.01413985,  0.02166083 , 0.01156313 ,-0.00591387, -0.02071469,
   0.03837214 ,-0.00367591]])
print(x)
it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

[[-0.01968568  0.00217895  0.00339866 -0.02325224 -0.0221614   0.02105142
   0.0290504  -0.03711821 -0.00844577  0.00813935 -0.01596476  0.00103281
  -0.0114362   0.01413985  0.02166083  0.01156313 -0.00591387 -0.02071469
   0.03837214 -0.00367591]]


In [22]:
print(np.ones((1,10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [32]:
pic = np.ones((3,4,4))
print(pic)
print(pic.shape)
print('---')
transform = np.pad(pic, ((0,0),(1,1),(1,1)), 'constant', constant_values= 0 )
print(transform)
print(transform.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(3, 4, 4)
---
[[[0. 0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0. 0.]]]
(3, 6, 6)


In [2]:
print(isinstance(2.0, int))

False


In [24]:
x = np.array([[[[1],[2]],[[3],[40]]],[[[5],[3]],[[2],[1]]]])

print(x.shape)
print(np.argmax(x, axis = 2))
ind = np.unravel_index(np.argmax(x, axis=None), x.shape)
print(ind)

(2, 2, 2, 1)
[[[1]
  [1]]

 [[0]
  [0]]]
(0, 1, 1, 0)


In [32]:
x = np.array([[1,2,3],[40,70,1]])
print(x)
ind1, ind2 = np.unravel_index(np.argmax(x, axis=None), x.shape)
print(ind1)
print(ind2)

[[ 1  2  3]
 [40 70  1]]
1
1


In [36]:
print(int(6/2))

3


In [70]:
a = np.arange(80)
b = a.reshape((5,4,2,2))
# print(b)
print('---')
c= b[:,1,:,:]
#print(c)
print('---')
d = c.reshape(-1)
#print(d)
print('---')
#print(d.reshape(5,1,2,2))

---
---
---


In [62]:
a = np.arange(4).reshape((2,2))
print(a)
print(np.sum(a, axis = 0))

[[0 1]
 [2 3]]
[2 4]


In [2]:
print(b.shape)
print('-------------------------------------')
e = np.array([b[:,i,:,:] for i in range(4)])
e = e.reshape(4,-1).T + 1
e = e.T.reshape(4,5,2,2)
e = np.array([e[:,i,:,:] for i in range(5)])
#print(e.reshape(4,-1).T)
print('-------------------------------------')
print(e.shape)

NameError: name 'b' is not defined

In [16]:
a = np.arange(96)
b = a.reshape((6,4,2,2))
c = np.split(b, 2)
print(c[1].shape)
print(type(c))
d= np.concatenate(c)
print(d.shape)

(3, 4, 2, 2)
<class 'list'>
(6, 4, 2, 2)


In [20]:
dir(torch.device)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'index',
 'type']